module.exports = {
    API_BASE_URL: process.env.API_BASE_URL,
    BOT_TOKEN: process.env.BOT_TOKEN,
    TEAM_CHANNEL_ID: process.env.TEAM_CHANNEL_ID,
    TEAM_CHANNEL_PREFIX: process.env.TEAM_CHANNEL_PREFIX,
    ADMIN_ID: process.env.ADMIN_ID,
    TZ: process.env.TZ,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_API_MODEL: process.env.OPENAI_API_MODEL,
    OPENAI_API_TEMPERATURE: process.env.OPENAI_API_TEMPERATURE,
    OPENAI_API_TOP_P: process.env.OPENAI_API_TOP_P,
    OPENAI_SESSION_TOKEN: process.env.OPENAI_SESSION_TOKEN,
    HOST: process.env.HOST,
    PORT: process.env.PORT,
    JIRA_API_URL: process.env.JIRA_API_URL,
    JIRA_ROOT_TASK_ID: process.env.JIRA_ROOT_TASK_ID,
    JIRA_BOT_USERNAME: process.env.JIRA_BOT_USERNAME,
    JIRA_BOT_PASSWORD: process.env.JIRA_BOT_PASSWORD,
};